[package]
name = "scheduled"
version = "1.0.0"
edition = "2021"
description = "A crate that offers event scheduling"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
queued_rust = "0.7.4"
